swagger: '2.0'
info:
  version: 1.0.0
  title: Pokemon
  x-ibm-name: pokemon
basePath: /pokemon
x-ibm-configuration:
  properties:
    target-url:
      value: https://pokeapi.co/api/v2/pokemon-species/
      description: URL of the proxy policy
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: blocklist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
paths:
  /species:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
schemes:
  - https
